info:
  description: API для роботи із системою
  title: RentJoy API
  version: 1.0.0
openapi: 3.0.0
paths:
  /api/product/add-product:
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                pCategory:
                  type: string
                pDescription:
                  type: string
                pName:
                  type: string
                pOffer:
                  type: string
                pPrice:
                  type: number
                pQuantity:
                  type: integer
                pStatus:
                  type: string
              required:
              - pName
              - pPrice
              - pQuantity
              - pCategory
              type: object
        required: true
      responses:
        '200':
          description: Продукт додано
      summary: Додати новий продукт
      tags:
      - Products
  /api/product/add-review:
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                pId:
                  type: string
                rating:
                  type: number
                review:
                  type: string
                uId:
                  type: string
              required:
              - pId
              - uId
              - rating
              type: object
        required: true
      responses:
        '200':
          description: Відгук додано
      summary: Додати відгук
      tags:
      - Products
  /api/product/cart-product:
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                productArray:
                  items:
                    type: string
                  type: array
              required:
              - productArray
              type: object
        required: true
      responses:
        '200':
          description: Товари в кошику
      summary: Отримати товари в кошику
      tags:
      - Products
  /api/product/delete-product:
    get:
      parameters:
      - in: query
        name: pId
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Продукт видалено
      summary: Видалити продукт
      tags:
      - Products
  /api/product/delete-review:
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                pId:
                  type: string
                rId:
                  type: string
              required:
              - rId
              - pId
              type: object
        required: true
      responses:
        '200':
          description: Відгук видалено
      summary: Видалити відгук
      tags:
      - Products
  /api/product/edit-product:
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                pCategory:
                  type: string
                pDescription:
                  type: string
                pId:
                  type: string
                pImages:
                  items:
                    type: string
                  type: array
                pName:
                  type: string
                pOffer:
                  type: string
                pPrice:
                  type: number
                pQuantity:
                  type: integer
                pStatus:
                  type: string
              required:
              - pId
              type: object
        required: true
      responses:
        '200':
          description: Продукт оновлено
      summary: Редагувати продукт
      tags:
      - Products
  /api/product/product-by-category:
    get:
      parameters:
      - in: query
        name: catId
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Список продуктів
      summary: Отримати продукти за категорією
      tags:
      - Products
  /api/product/product-by-price:
    get:
      parameters:
      - in: query
        name: price
        required: true
        schema:
          type: number
      responses:
        '200':
          description: Список продуктів
      summary: Отримати продукти за ціною
      tags:
      - Products
  /api/product/single-product:
    get:
      parameters:
      - in: query
        name: pId
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Дані продукту
      summary: Отримати продукт за ID
      tags:
      - Products
  /api/product/all-product:
    get:
      summary: Отримати всі продукти
      tags:
        - Products
      responses:
        '200':
          description: Успішна відповідь
          content:
            application/json:
              schema:
                type: array
        '500':
          description: Внутрішня помилка сервера
  /api/product/wish-product:
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                productArray:
                  items:
                    type: string
                  type: array
              required:
              - productArray
              type: object
        required: true
      responses:
        '200':
          description: Список улюбленого
      summary: Отримати список улюблених продуктів
      tags:
      - Products
  
  /api/user/add-user:
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                address:
                  type: string
                allProduct:
                  items:
                    type: string
                  type: array
                amount:
                  type: number
                phone:
                  type: string
                transactionId:
                  type: string
                user:
                  type: string
              required:
              - allProduct
              - user
              - amount
              - transactionId
              - address
              - phone
              type: object
        required: true
      responses:
        '200':
          description: Користувача успішно створено
      summary: Додати нового користувача
      tags:
      - Users
  /api/user/all-user:
    get:
      responses:
        '200':
          description: Список користувачів
      summary: Отримати всіх користувачів
      tags:
      - Users
  /api/user/change-password:
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                newPassword:
                  type: string
                oldPassword:
                  type: string
                uId:
                  type: string
              required:
              - uId
              - oldPassword
              - newPassword
              type: object
        required: true
      responses:
        '200':
          description: Пароль змінено
      summary: Змінити пароль користувача
      tags:
      - Users
  /api/user/delete-user:
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                uId:
                  type: string
              required:
              - uId
              type: object
        required: true
      responses:
        '200':
          description: Користувача видалено
      summary: Видалити користувача
      tags:
      - Users
  /api/user/edit-user:
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                address:
                  type: string
                allProduct:
                  items:
                    type: string
                  type: array
                amount:
                  type: number
                phone:
                  type: string
                transactionId:
                  type: string
                uId:
                  type: string
                user:
                  type: string
              required:
              - uId
              type: object
        required: true
      responses:
        '200':
          description: Користувача оновлено
      summary: Редагувати користувача
      tags:
      - Users
  /api/user/signle-user:
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                uId:
                  type: string
              required:
              - uId
              type: object
        required: true
      responses:
        '200':
          description: Дані користувача
      summary: Отримати користувача за ID
      tags:
      - Users
  
  /api/order/create-order:
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                address:
                  type: string
                allProduct:
                  items:
                    type: string
                  type: array
                amount:
                  type: number
                phone:
                  type: string
                transactionId:
                  type: string
                user:
                  type: string
              required:
              - allProduct
              - user
              - amount
              - transactionId
              - address
              - phone
              type: object
        required: true
      responses:
        '200':
          description: Замовлення створено
      summary: Створити нове замовлення
      tags:
      - Orders
  /api/order/delete-order:
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                orderId:
                  type: string
              required:
              - orderId
              type: object
        required: true
      responses:
        '200':
          description: Замовлення видалено
      summary: Видалити замовлення
      tags:
      - Orders
  /api/order/get-all-orders:
    get:
      responses:
        '200':
          description: Список замовлень
      summary: Отримати всі замовлення
      tags:
      - Orders
  /api/order/order-by-user:
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                uId:
                  type: string
              required:
              - uId
              type: object
        required: true
      responses:
        '200':
          description: Замовлення користувача
      summary: Отримати замовлення користувача
      tags:
      - Orders
  /api/order/update-order:
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                address:
                  type: string
                allProduct:
                  items:
                    type: string
                  type: array
                amount:
                  type: number
                orderId:
                  type: string
                phone:
                  type: string
                transactionId:
                  type: string
                user:
                  type: string
              required:
              - orderId
              type: object
        required: true
      responses:
        '200':
          description: Замовлення оновлено
      summary: Оновити замовлення
      tags:
      - Orders

  /api/category/add-category:
    post:
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                cDescription:
                  type: string
                cImage:
                  format: binary
                  type: string
                cName:
                  type: string
                cStatus:
                  type: string
              required:
              - cName
              - cImage
              type: object
        required: true
      responses:
        '200':
          description: Категорію створено
      summary: Додати нову категорію
      tags:
      - Categories
  /api/category/all-category:
    get:
      responses:
        '200':
          description: Список категорій
      summary: Отримати всі категорії
      tags:
      - Categories
  /api/category/delete-category:
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                cId:
                  type: string
              required:
              - cId
              type: object
        required: true
      responses:
        '200':
          description: Категорію видалено
      summary: Видалити категорію
      tags:
      - Categories
  /api/category/edit-category:
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                cDescription:
                  type: string
                cId:
                  type: string
                cName:
                  type: string
                cStatus:
                  type: string
              required:
              - cId
              type: object
        required: true
      responses:
        '200':
          description: Категорію оновлено
      summary: Редагувати категорію
      tags:
      - Categories

  /api/auth/isadmin:
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                uId:
                  type: string
              required:
              - uId
              type: object
        required: true
      responses:
        '200':
          description: Результат перевірки адміністратора
      summary: Перевірити, чи є користувач адміністратором
      tags:
      - Auth
  /api/auth/signin:
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
              type: object
        required: true
      responses:
        '200':
          description: Успішна авторизація
      summary: Авторизація користувача
      tags:
      - Auth
  /api/auth/signup:
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                cPassword:
                  type: string
                email:
                  type: string
                name:
                  type: string
                password:
                  type: string
                userRole:
                  type: string
              required:
              - name
              - email
              - password
              - cPassword
              - userRole
              type: object
        required: true
      responses:
        '200':
          description: Користувача зареєстровано
      summary: Реєстрація нового користувача
      tags:
      - Auth
  /api/auth/user:
    post:
      responses:
        '200':
          description: Список користувачів
      summary: Отримати всіх користувачів (доступно лише адміну)
      tags:
      - Auth
servers:
- description: Локальний сервер
  url: http://localhost:8000


components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: string
          example: "67db07d60cdd5e2458c6c996"
        pName:
          type: string
          example: "Camera"
        pDescription:
          type: string
          example: "Equipment for photo studio."
        pPrice:
          type: number
          example: 500
        pOffer:
          type: string
          example: "33"
        pQuantity:
          type: integer
          example: 750
        pSold:
          type: integer
          example: 0
        pImages:
          type: array
          items:
            type: string
          example:
            - "1742407638027_2048x1364.jpg"
            - "1742407638032_ecommerce-photography-setup.jpg"
        pCategory:
          type: object
          properties:
            _id:
              type: string
              example: "67db067b0cdd5e2458c6c98c"
            cName:
              type: string
              example: "Photo"
        pStatus:
          type: string
          example: "Active"
        pRatingsReviews:
          type: array
          items:
            type: object
          example: []
        createdAt:
          type: string
          format: date-time
          example: "2025-03-19T18:07:18.038Z"
        updatedAt:
          type: string
          format: date-time
          example: "2025-03-19T18:07:18.038Z"
        __v:
          type: integer
          example: 0
